In [1]:
import pandas as pd

In [4]:
df_flexi = pd.read_csv("../../data/transformed/flexicar.es.csv")
df_mil = pd.read_csv("../../data/transformed/milanuncios_predi.csv")
df_mil

,car_type,year,price,km,photo_url,prediccion
0,TESLA - MODEL 3,2022,32990,67405,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
1,TESLA - MODEL S,2019,46500,37500,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
2,TESLA - MODEL X,2018,37490,140261,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
3,TESLA - MODEL Y,2023,36900,33000,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
4,TESLA - MODEL Y,2023,44990,29000,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
...,...,...,...,...,...,...
1856,CUPRA - LEON,2025,34305,0,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
1857,CUPRA - LEON,2025,28885,0,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
1858,CUPRA - FORMENTOR,2025,49400,3500,https://images.milanuncios.com/api/v1/ma-ad-me...,neutral
1859,CUPRA - LEON,2025,44600,0,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno
1860,CUPRA - FORMENTOR,2022,28900,35200,https://images.milanuncios.com/api/v1/ma-ad-me...,bueno

In [8]:
df_total = pd.concat([df_flexi, df_mil], ignore_index=True)
df_total

,photo_url,car_type,year,price,km,prediccion
0,https://www.flexicar.es/images/903000000147499...,BMW Serie 1,2021,19490,85977,neutral
1,https://www.flexicar.es/images/903000000161152...,Audi A1,2017,16490,48836,neutral
2,https://www.flexicar.es/images/903000000151458...,BMW Z4,2022,40790,54486,neutral
3,https://www.flexicar.es/images/903000000150512...,BMW Serie 1,2020,21590,61215,neutral
4,https://www.flexicar.es/images/903000000149232...,BMW Serie 1,2022,23990,93881,neutral
...,...,...,...,...,...,...
2987,https://images.milanuncios.com/api/v1/ma-ad-me...,CUPRA - LEON,2025,34305,0,bueno
2988,https://images.milanuncios.com/api/v1/ma-ad-me...,CUPRA - LEON,2025,28885,0,bueno
2989,https://images.milanuncios.com/api/v1/ma-ad-me...,CUPRA - FORMENTOR,2025,49400,3500,neutral
2990,https://images.milanuncios.com/api/v1/ma-ad-me...,CUPRA - LEON,2025,44600,0,bueno
2991,https://images.milanuncios.com/api/v1/ma-ad-me...,CUPRA - FORMENTOR,2022,28900,35200,bueno

In [13]:
df_total = df_total[df_total['car_type'] != 'BMW - SERIE']

In [15]:
df_total['car_type'] = df_total['car_type'].str.upper()

C:\Users\victo\AppData\Local\Temp\ipykernel_22040\754666513.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total['car_type'] = df_total['car_type'].str.upper()

In [23]:
df_total['car_type'].unique()

array(['BMW - SERIE 1', 'AUDI - A1', 'BMW - Z4', 'AUDI - Q7', 'AUDI - Q2',
       'AUDI - Q3', 'BMW - X2', 'BMW - SERIE 2', 'AUDI - Q5', 'BMW - X4',
       'BMW - X1', 'AUDI - A3', 'BMW - X3', 'BMW - X5', 'BMW - SERIE 3',
       'BMW - SERIE 5', 'BMW - X6', 'BMW - SERIE 4', 'AUDI - A4',
       'AUDI - A7', 'AUDI - A6', 'AUDI - A5', 'BMW - SERIE 7', 'BMW - I3',
       'PORSCHE - MACAN', 'BMW - SERIE 6', 'TESLA - MODEL 3',
       'TESLA - MODEL S', 'TESLA - MODEL X', 'TESLA - MODEL Y',
       'AUDI - TT', 'BMW - COMPACT', 'PORSCHE - CAYENNE',
       'PORSCHE - TAYCAN', 'PORSCHE - PANAMERA', 'PORSCHE - 911',
       'PORSCHE - BOXSTER', 'CUPRA - FORMENTOR', 'CUPRA - TERRAMAR',
       'CUPRA - LEON', 'CUPRA - BORN', 'CUPRA - ATECA'], dtype=object)

In [17]:
marcas = ['BMW', 'AUDI', 'TESLA', 'PORSCHE', 'CUPRA']

def formatear_car_type(valor):
    if pd.isna(valor):
        return valor
    valor = str(valor).upper().strip()
    for marca in marcas:
        if valor.startswith(marca):
            resto = valor[len(marca):].strip()
            # Si ya tiene el guion, no lo agregamos
            if resto.startswith('-'):
                resto = resto[1:].strip()
            return f"{marca} - {resto}"
    return valor  # Si no detectamos ninguna marca, lo dejamos igual

# Aplicamos al dataframe
df_total['car_type'] = df_total['car_type'].apply(formatear_car_type)

C:\Users\victo\AppData\Local\Temp\ipykernel_22040\856760251.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total['car_type'] = df_total['car_type'].apply(formatear_car_type)

In [19]:
modelos_equivalentes = {
    'AUDI - Q3 SPORTBACK': 'AUDI - Q3',
    'AUDI - Q5 SPORTBACK': 'AUDI - Q5',
    'BMW - SERIE 2 GRAN TOURER': 'BMW - SERIE 2',
    'BMW - SERIE 2 ACTIVE TOURER': 'BMW - SERIE 2',
}

df_total['car_type'] = df_total['car_type'].replace(modelos_equivalentes)

C:\Users\victo\AppData\Local\Temp\ipykernel_22040\1233598218.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total['car_type'] = df_total['car_type'].replace(modelos_equivalentes)

In [24]:
df_total.to_csv("../../data/processed/full_data.csv", index=False)